packageExtensions:
  '@theunderscorer/nx-semantic-release@*':
    peerDependencies:
      '@semantic-release/commit-analyzer': '*'
      '@semantic-release/release-notes-generator': '*'
  chalk@5.0.1:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
  semantic-release-plugin-decorators@*:
    peerDependencies:
      '@semantic-release/changelog': '*'
      '@semantic-release/commit-analyzer': '*'
      '@semantic-release/exec': '*'
      '@semantic-release/git': '*'
      '@semantic-release/github': '*'
      '@semantic-release/npm': '*'
      '@semantic-release/release-notes-generator': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.4.cjs
