[workspace]
members = [
    "packages/hooks-core",
    "packages/hooks-macro-core",
    "packages/hooks-macro",
    "packages/hooks",
    "packages/hooks-test",
]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
