[workspace]
members = [
    "packages/hooks-core",
    "packages/hooks-derive-core",
    "packages/hooks-derive",
    "packages/hooks",
    # "packages/hooks-test",
]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
