[package]
name = "hooks-derive"
version = "1.0.0-alpha.8"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
hooks-derive-core = { path = "../hooks-derive-core", version = "1.0.0-alpha.8" }
