[package]
name = "hooks-derive-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = "1.0.102"
darling = "0.14.1"

[dev-dependencies]
hooks = { path = "../hooks" }

[features]
extra-traits = []
