[package]
name = "hooks"
version = "1.0.0-alpha.2"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hooks-derive = { path = "../hooks-derive", version = "1.0.0-alpha.1" }
