[package]
name = "hooks"
version = "2.3.0-alpha"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hooks-macro = { path = "../hooks-macro", version = "0.1.1", optional = true }
hooks-core = { path = "../hooks-core", version = "2.2.0-alpha", default-features = false }
pin-project-lite = "0.2.9"

[dependencies.smallvec]
version = "1.10.0"
optional = true
features = ["const_generics"]

[dev-dependencies]
futures-lite = "1.12.0"

[features]
default = ["futures-core", "all"]
proc-macro = ["hooks-macro"]
futures-core = ["hooks-core/futures-core"]
all = [
    "use_debug",
    "use_default_pinned",
    "use_effect",
    "use_lazy_pinned",
    "use_lazy_pinned_hook",
    "use_memo",
    "use_mut",
    "use_poll_next_update",
    "use_shared_ref",
    "use_shared_state",
    "use_state",
    "use_uninitialized_hook",
]
ShareValue = []
use_debug = []
use_default_pinned = []
use_effect = []
use_lazy_pinned = ["use_default_pinned"]
use_lazy_pinned_hook = []
use_memo = []
use_mut = []
use_poll_next_update = []
use_shared_ref = ["ShareValue"]
use_shared_state = ["use_shared_ref"]
use_state = ["smallvec"]
use_uninitialized_hook = []

[package.metadata.docs.rs]
all-features = true
