[package]
name = "hooks"
version = "1.0.1-alpha.21"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hooks-derive = { path = "../hooks-derive", version = "1.0.1-alpha.8", optional = true }
hooks-core = { path = "../hooks-core", version = "1.0.0-alpha.10", default-features = false }
pin-project-lite = "0.2.9"
smallvec = { version = "1.10.0", features = ["const_generics"] }
lazy-pinned = { version = "0.1.0", optional = true }

[dev-dependencies]
futures-lite = "1.12.0"

[features]
default = ["derive", "futures-core", "all"]
derive = ["hooks-derive"]
futures-core = ["hooks-core/futures-core"]
all = [
    "use_debug",
    "use_default_pinned",
    "use_effect",
    "use_lazy_pinned",
    "use_lazy_pinned_hook",
    "use_memo",
    "use_mut",
    "use_poll_next_update",
    "use_shared_ref",
    "use_shared_state",
    "use_state",
    "use_uninitialized_hook",
]
ShareValue = []
use_debug = []
use_default_pinned = []
use_effect = []
use_lazy_pinned = ["lazy-pinned", "use_default_pinned"]
use_lazy_pinned_hook = ["lazy-pinned"]
use_memo = []
use_mut = []
use_poll_next_update = []
use_shared_ref = ["ShareValue"]
use_shared_state = ["use_shared_ref"]
use_state = []
use_uninitialized_hook = []
