[package]
name = "hooks-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
hooks = { path = "../hooks" }
insta = "1.21.0"
prettyplease = "0.1.21"
futures-lite = "1.12.0"

[dev-dependencies.hooks-derive-core]
path = "../hooks-derive-core"
features = [
  "extra-traits",
]
