[package]
name = "hooks-test"
version = "0.1.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
hooks = { path = "../hooks", features = ["proc-macro"] }
insta = "1.21.0"
prettyplease = "0.1.21"
futures-lite = "1.12.0"
smol = "1.2.5"

[dev-dependencies.hooks-macro-core]
path = "../hooks-macro-core"
features = ["extra-traits"]
