[package]
name = "hooks-core"
version = "2.1.0-alpha"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.9"
futures-core = { version = "0.3.25", optional = true }
syn-lite = "0.1.0"

[dev-dependencies]
hooks_dev = { path = "../hooks", package = "hooks", features = ["proc-macro"] }

[features]
default = ["futures-core"]
