[package]
name = "hooks-core"
version = "1.0.0-alpha.9"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.9"
futures-core = { version = "0.3.25", optional = true }

[dev-dependencies]
hooks = { path = "../hooks" }

[features]
default = ["futures-core"]
