[package]
name = "hooks-frender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hooks = { version = "1.0.0-alpha.17", path = "../hooks" }
bg = "0.1.1"
gloo = { version = "0.8.0", features = ["futures"] }
wasm-bindgen = "0.2.83"
# async-executor = "1.5.0"
wasm-bindgen-futures = "0.4.33"
pin-project-lite = "0.2.9"
futures-io = "0.3.25"
html-escape = "0.2.13"

[dependencies.futures-lite]
version = "1.12.0"
# default-features = false

[dependencies.web-sys]
version = "0.3.60"
features = [
    #
    "Node",
    "MouseEvent",
    "Text",
    "HtmlButtonElement",
]
