[package]
name = "hooks-macro"
version = "1.0.1-alpha.8"
edition = "2021"
description = "Compile-time, async hooks"
license = "MIT"
documentation = "https://docs.rs/hooks"
repository = "https://github.com/frender-rs/hooks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
hooks-macro-core = { path = "../hooks-macro-core", version = "1.1.0-alpha.8" }
