name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-edit@0.11.3

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: yarn install --immutable

      - name: Test
        run: |
          cargo fmt --all --check
          cargo check --locked --all-targets
          cargo clippy --locked --all-targets -- --deny warnings
          cargo test

      - name: release
        run: |
          yarn nx run hooks-core:semantic-release
          yarn nx run hooks-derive-core:semantic-release
          yarn nx run hooks-derive:semantic-release
          yarn nx run hooks:semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          HUSKY: 0
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
