on:
  push:
    branches:
      - alpha
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: |
          cargo fmt --all --check
          cargo check --locked --all-targets
          cargo check -p hooks --no-default-features --locked
          cargo clippy --locked --all-targets -- --deny warnings
          cargo test
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: alpha
      - name: Publish
        run: |
          echo $PATHS_RELEASED | while read -r $dir_path
          do
            echo "publish $dir_path/Cargo.toml"
            cargo publish --manifest-path "$dir_path/Cargo.toml"
          done
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          PATHS_RELEASED: ${{ join(fromJSON(steps.release.outputs.paths_released), '\n') }}
        if: ${{ steps.release.outputs.releases_created }}
