on:
  push:
    branches:
      - alpha
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: |
          cargo fmt --all --check
          cargo check --locked --all-targets --all-features
          cargo clippy --locked --all-targets --all-features -- --deny warnings
          cargo test -p hooks-core
          bash scripts/test-hooks.sh
          cargo test -p hooks-test
          cargo test
          cargo test --all-features
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: alpha
      - name: Publish
        run: |
          echo $PATHS_RELEASED | while read -r dir_path
          do
            if [[ $dir_path -ef packages/hooks-test ]]; then
              continue
            fi
            echo "publish $dir_path/Cargo.toml"
            cargo publish --manifest-path "$dir_path/Cargo.toml"
          done
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          PATHS_RELEASED: ${{ join(fromJSON(steps.release.outputs.paths_released || '[]'), '\n') }}
        if: ${{ steps.release.outputs.releases_created }}
